name: Question
description: Ask a question about using Cyberdriver Desktop or connecting to Cyberdriver API.
title: "[Question]: "
labels: ["question"]
body:
  - type: textarea
    id: question
    attributes:
      label: What do you need help with?
    validations:
      required: true
  - type: input
    id: versions
    attributes:
      label: Version details
      description: Cyberdriver Desktop version and, if applicable, local API version.
  - type: textarea
    id: context
    attributes:
      label: Context
      description: Steps tried, expected behavior, and any logs or screenshots.

